<?php
/**
 * @file english.inc.php
 * @brief Contenu d'accueil affiche en anglais sur la page d'index.
 * @author BAARIR Fatma-Zahra
 * @author PHUNG Enzo
 *
 * @details This fragment is included dynamically by `index.php` when the
 * English version of the home page is requested. It mirrors the French
 * welcome page while keeping the same navigation structure.
 */
?>
<?php
/**
 * Main title and introductory text for the English home page.
 *
 * This introductory block explains the academic context of the project
 * before the user navigates to the individual tutorials.
 */
?>
<h1>Welcome to our tutorial site</h1>

<p>
This site contains the exercises completed as part of the web development module (L2 Computer Science).
</p>
<section>
<?php
/**
 * Presentation section describing the academic context of the website.
 *
 * It explains that the site gathers several practical assignments completed
 * during the semester.
 */
?>
<h2>Presentation</h2>
<p>
	This website was created as part of the web development module
	in the second year of Computer Science studies. It compiles the various practical exercises
	completed during the semester.
</p>
<p>
	Each tutorial includes exercises to practice PHP,
	function creation, array manipulation, and
	dynamic HTML content generation.
</p>
</section>
<section>
<?php
/**
 * Goals section listing the main learning objectives.
 *
 * These points summarize the technical skills practiced throughout the site.
 */
?>
<h2>Goals</h2>
<ul>
	<li>Learn to use PHP to generate HTML</li>
	<li>Create and use functions</li>
	<li>Manipulate PHP arrays</li>
	<li>Structure a website with reusable files (header, footer)</li>
</ul>
</section>
<section>
<?php
/**
 * Navigation section explaining how to browse the tutorials.
 *
 * It gives readers enough context to understand how the tutorials are
 * organized before using the main navigation.
 */
?>
<h2>Navigation</h2>
<p>
	Use the navigation menu to access the different tutorials.
	Each page contains the exercises and the results generated by the PHP scripts.
	Find the site map at the bottom of the page.
</p>
<p>
	Tutorial 10 is still under construction.
</p>
</section>
<section class="practice-links">
<?php
/**
 * Direct links to each practical exercise page.
 *
 * This shortcut list complements the main header navigation from inside
 * the home page content itself.
 */
?>
<h2>Practical Exercises</h2>

<ul>
	<li>
		<a href="td5.php<?= "?style=" . $style ?>" class="link-btn">Tutorial 5 - HTML Functions and Tables</a>
	</li>

	<li>
		<a href="td6.php<?= "?style=" . $style ?>" class="link-btn">Tutorial 6 - Functions, Constants, and
			Factorization</a>
	</li>
	<li>
		<a href="td7.php<?= "?style=" . $style ?>" class="link-btn">utorial 7 - PHP Arrays and Functions</a>
	</li>
	<li>
		<a href="td8.php<?= "?style=" . $style ?>" class="link-btn">Tutorial 8 - PHP - arrays, functions and
			parameterized links</a>
	</li>
	<li>
		<a href="td9.php<?= "?style=" . $style ?>" class="link-btn">Tutorial 9 - HTML forms and PHP processing</a>
	</li>
	<li>
		<a href="td10.php<?= "?style=" . $style ?>" class="link-btn">Tutorial 10 - Under Construction</a>
	</li>
</ul>
</section>
